### ISSUE TITLE
使用交换粘土球击中匠魂的史莱姆后，会引发崩溃

### ISSUE THREAD

**Issue by XxttCrystal** [rawchickenNEG/ClayNoMoreBalanced#5]
使用交换粘土球击中匠魂的史莱姆后，会引发崩溃
我的报错文件丢了（
作者可以试试自己复现一下
如果不能复现我再提供报错（但可能得很久，由于特殊原因）

**Comment by rawchickenNEG** [comment]
已修复，在新版本内会应用。

**Comment by XxttCrystal** [comment]
太感谢了！
非常喜欢你的mod，我已经加入到我的整合包并且单独作为一个任务支线了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月12日(星期一) 凌晨0:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rawchickenNEG/ClayNoMoreBalanced] 使用交换粘土球击中匠魂的史莱姆后，会引发崩溃 (Issue #5)





 
已修复，在新版本内会应用。
